import React from 'react';

const Dcontributiondata=[
	{	id:'0',
		name:'Mariana',
		text:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
		img:'https://www.fotor.com/blog/wp-content/uploads/2019/10/12.blur-photo.png',
	},
		
		{id:'1',
		name:'Harry',
		text:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
		img:'https://st2.depositphotos.com/2931363/6819/i/600/depositphotos_68197553-stock-photo-handsome-young-man-making-selfie.jpg',
	},
		
		{name:'Lily',
		id:'2',
		text:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
		img:'https://xoxobella.com/wp-content/uploads/2020/06/instagram_captions_for_selfies_and-_selfie_puns_bella_bucchiotti-4.jpg',
	},
		{name:'Vyomesh',
		id:'3',
		text:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
		img:'https://st.focusedcollection.com/18590116/i/650/focused_227260878-stock-photo-close-man-posing-selfie.jpg',
	},
		{name:'Jalandhar',
		id:'4',
		text:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
		img:'https://c8.alamy.com/comp/J29KW0/athletic-asian-man-taking-a-selfie-during-a-morning-run-J29KW0.jpg',
	},
		{name:'Eddie',
		id:'5',
		text:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
		img:'https://c8.alamy.com/comp/GD2473/one-young-male-asian-or-chinese-college-students-looking-at-camera-GD2473.jpg',
	},
		{name:'Justin',
		id:'6',
		text:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
		img:'https://previews.123rf.com/images/sevendeman/sevendeman2001/sevendeman200100063/137683275-happy-asian-man-selfie-in-his-condominium-room-.jpg',
	},
		{name:'Andrew',
		id:'7',
		text:'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
		img:'https://c8.alamy.com/comp/F7JGF8/portrait-of-a-smiling-asian-male-student-standing-with-arms-folded-F7JGF8.jpg',
	},
]

export default Dcontributiondata;