import React from "react";
import Dcardselfhealing from "./Dcardselfhealing";

const Dmedibeni=()=>{
	
	return(<>
		<div className="container" style={{textAlign:'justify',color:'white',paddingLeft:'25px',paddingRight:'25px'}} id="selfhealdatadiv">	
		  <div className="row">
			<h1 style={{textAlign:'center'}} id="text_pink">Five Amazing Benefits of Meditation</h1><br/>
			<Dcardselfhealing img="https://isha.sadhguru.org/yoga/wp-content/uploads/2020/05/benefits-of-meditation-spiritual.jpg"/><br/><br/>
			Meditation is a powerful tool for spiritual growth, and is essentially a process to take one beyond the limitations of body and mind. Teachers and practitioners of these “inner technologies” have also experienced the many physical and mental benefits of meditation and Yoga. In recent years, a growing number of scientific studies and research on meditation have corroborated these experiences. Isha’s introductory practice is the Shambhavi Mahamudra, an ancient kriya that has millions of dedicated practitioners who aver that they experience greater emotional balance, concentration, focus, stability and better health with regular practice of the meditation. In fact, there have been several scientific studies that measure the various benefits of practicing the kriya regularly – both with regard to brain activity during the kriya, as well as statistical research of how it affects people’s health and well-being.<br/><br/>
			<h3 style={{textAlign:'center'}} id="text_pink">How does the Kriya Work?</h3><br/><br/>
			The reason why most people are unhappy or unhealthy is that the physical, the mental and the “pranic” body are not in alignment. Sadhguru says, “There is a certain way to engineer our system, to make this body, to make this mind… the very chemistry within us the way we want it.” Traditionally, Yoga sees the human being as five layers of body: the physical body, the mental body, the pranic energy body, the etheric body and the bliss body. The reason why most people are unhappy or unhealthy is that the physical, the mental and the “pranic” body are not in alignment. Sadhguru explains, “If they are properly aligned, a natural expression, an overwhelming expression of joyfulness will naturally happen within a human being. Now, we are looking at the technology of keeping these three bodies constantly aligned so that joyfulness is not an accidental happening; joyfulness becomes a normal condition, a natural way of living for you.”<br/><br/>
			<h3 style={{textAlign:'center'}} id="text_pink">Studies on Shambhavi Mahamudra</h3><br/><br/>
			Studies on Shambhavi Mahamudra have been varied: some have examined its impact on disease status and medicine usage, some have looked specifically at menstrual disorders, while others have studied the benefits of this meditation on sleep, heart rate variability, brain activity, etc. Other studies have researched general well-being and improved attention spans among regular meditators. Let’s take a look at the results of some of the key studies.<br/><br/>
			<h3 style={{textAlign:'center'}} id="text_pink">Benefits of meditation #1: Improved cardiac health</h3><br/><br/>
			Two studies published in 2008 and 2012 examined how Shambhavi Mahamudra supported cardiac health. The studies showed that participants had a more well-balanced Cardiac Autonomic Nervous System and an overall increase in Heart Rate Variability (HRV) during the practice. A higher HRV has been linked to better immunity to stressful situations, and is said to bestow a greater survival advantage on individuals. A lower HRV on the other hand has been linked to various heart diseases such as coronary artery disease, hypertension, chronic heart failure and myocardial infarction. The researchers conclude that practitioners of the Shambhavi Mahamudra and other Isha Yoga practices have higher exercise tolerance, better cardiac response to stressful situation, lower probability of undergoing hypertension of cardiac troubles such as ischemia or infarction.<br/><br/>
			<h3 style={{textAlign:'center'}} id="text_pink">Benefits of meditation #2: Greater coherence within the brain</h3><br/><br/>
			A study from the Centre for Biomedical Engineering, IIT Delhi, looked at EEG (Electroencephalography) data from practitioner’s brains before, during and after practicing the kriya. The results show that practitioners experienced a greater level of coherence between the right and left hemispheres of the brain. EEG coherence is known to be a measure of how well connected various regions of the brain are. Higher coherence indicates greater exchange of information between various regions, as well as improved functional coupling and coordination. Higher levels of coherence are also correlated to higher scores on IQ and creativity tests, as well emotional stability and cognitive flexibility. The researchers also measured signals at various prominent EEG spectral bands known as the alpha, beta, delta and theta. Shambhavi practitioners were seen to have higher alpha band power in general, indicating that they experienced lower stress levels. There was a high increase in delta band power and theta band and a notable reduction in beta band power. A reduction in beta band power indicates reduced susceptibility to mental tension, excitement and anxiety. Higher theta and delta activity have been noted in previous research as indicative of conscious access to deeper states of meditation. “Delta rhythms combined with alpha are known to reflect an inner intuitive empathetic radar, a kind of sixth sense” the researchers note.<br/><br/>
			<h3 style={{textAlign:'center'}} id="text_pink">Benefits of meditation #3: Improved sleep</h3><br/><br/>
			A study presented at the 20th Congress of the European Sleep Research Society, Lisbon, Portugal compared the sleep patterns of 15 male meditators with a control group of 15 age and education-matched, male non-meditators. Participants were aged between 25 and 55 years. The meditators had practiced Shambhavi Mahamudra as well as other Isha Yoga practices. Whole-night polysomnographic measures were recorded in participants and EEG data was recorded, along with other parameters. The results showed that the percentage of REM sleep, sleep efficiency and total sleep time of meditators was significantly higher as compared to the control group of non-meditators. Meditators also experienced better sleep quality as evidenced by fewer awakenings after sleep onset. The study concludes that consistent practice of the Shambhavi meditation has a positive impact on quality of sleep.<br/><br/>
			<h3 style={{textAlign:'center'}} id="text_pink">Benefits of meditation #4: Improved attention and focus</h3><br/><br/>
			A study, published in the journal Perception, looked at how 89 participants performed in the Stroop task and attentional blink task before and after a 3-month Isha Yoga meditation retreat. The Stroop task looks at interference in the reaction time of a task. For example, when the name of a color is printed in some other color (for example, “red” is printed in black), respondents can make errors in identifying the printing color. Participants of the study were prone to fewer errors after the retreat than before it. Similarly, the attentional blink task involves participants identifying various visual stimuli presented to them within extremely short durations. Participants showed 58% correct detection during pre-retreat tests and 69% correct detection in post-retreat tests. The researchers conclude that “the hypothesis that meditation tends to improve allocation of attentional resources.” A similar study by a team from the Université de Toulouse, Department of Psychiatry and Human Behaviour, UC Irvine and the Indiana University School of Medicine looked at how Isha Yoga practices improve performance in attentional tasks due to better allocation of attentional resources, an ability to sustain attention and focus, faster re-allocation of attentional resources, greater cognitive flexibility and a reduction in automatic response. The study observes that these improvements are likely due to structural, anatomical and functional changes in meditators’ cognitive systems as compared to control groups drawn from the general population.<br/><br/>
			<h3 style={{textAlign:'center'}} id="text_pink">Benefits of meditation #5: Reduced menstrual disorders</h3><br/><br/>
			75% of women are thought to experience problems related to menstruation, which has a huge physical, psychological, social and economic impact on their life. The primary means of treatment for such issues are known to offer less than satisfactory relief, even when patients choose surgery as a last resort. Currently, Yoga has become very popular as one of the mainstay alternate treatments for many disorders. The benefits of meditation and Yoga in relation with such ailments have been under study for a while and show great promise. A team from the Indiana University School of Medicine, conducted a questionnaire survey of 128 female practitioners of the Shambhavi Mahamudra between the age group of 14 and 55 years, from the USA, UK, Singapore, Malaysia and Lebanon. 72% of the respondents practiced every day and the rest practiced 1-3 times in a week. The questionnaire asked respondents about the prevalence and impact of various menstrual disorders before they began the kriya and after they had practiced it for at least six months. Disorders covered included Dysmennorhea, symptoms of premenstrual syndrome, heaviness of menstrual flow, irregularity of menstrual cycle, the need for medical or surgical intervention for disorders, and the impairment of work during the menstrual period. The results showed a 57% decrease in the impact of Dysmennorhea, a 72% decrease in psychological symptoms such as irritability, mood swings, crying spells, depression and arguments, a 40% decrease in breast swelling and tenderness, and a 50% decrease in bloating and weight gain. There was an 87% decrease in the incidence of severe menstrual flow and an 80% decrease in the irregularity of the cycle. There was a 63% reduction in the need for medical or surgical interventions, and an 83% reduction in the number of instances of impairment at work. The authors conclude that the kriya “can be considered as an adjunct therapy for menstrual disorders given the improved symptoms in all the parameters.”<br/><br/>
			<h3 style={{textAlign:'center'}} id="text_pink">Other benefits of meditation</h3><br/><br/>
			In a questionnaire asking about improvements in life experienced from practicing the Shambhavi Mahamudra, 536 respondents indicated how the kriya had helped reduce medication and eliminate problems such as depression, allergies, asthma and other ailments. 91% reported greater inner peace, 87% reported improved emotional balance, 80% experienced greater mental clarity, 79% experienced increased energy levels, 74% reported improved self confidence and 70% reported better concentration and higher productivity. Among meditators who had been suffering depression, 87% reported improvement, 25% reduced their medication, and 50% were able to stop their medication. Similarly, for those suffering anxiety, 86% reported improvement, 28% reduced their medication, and 50% were able to stop their medication. Among those with insomnia, 73% reported improvement, 40% reduced their medication, and 30% were able to stop their medication. Similar improvements were seen for those with poor resistance to colds and flu, those who had suffered from headaches, asthma, fibromyalgia, gastrointestinal disorder, diabetes, hypertension, heart disease and a range of other chronic ailments.<br/><br/>
			<h3 style={{textAlign:'center'}} id="text_pink">In brief</h3><br/><br/>
			Taken together, all these results support a drop in stress and anxiety, a boost in mental alertness and focus, and an increase in self-awareness due to practicing the Shambhavi Mahamudra. It is also clear that regular practice benefits cardiac health and either leads to a stop in the use of medication or at least reduces it considerably for a range of ailments including hypertension, depression and menstrual issues.
			
           </div>
		</div>

		
	</>)
}

export default Dmedibeni;